steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash' # Use bash to set env var directly before command
  args:
    - '-c'
    - |
      export DOCKER_BUILDKIT=1
      docker build \
        --build-arg MAXMIND_ACCOUNT_ID=${_MAXMIND_ACCOUNT_ID} \
        --build-arg MAXMIND_LICENSE_KEY=${_MAXMIND_LICENSE_KEY} \
        -t gcr.io/${PROJECT_ID}/echoip .
  id: 'Build_New_Image_With_Latest_MaxMind_DB'
  timeout: '900s'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/${PROJECT_ID}/echoip'
  id: 'Push_Image_To_Container_Registry'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'echoip'
    - '--image'
    - 'gcr.io/${PROJECT_ID}/echoip'
    - '--project'
    - '${PROJECT_ID}'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
  id: 'Deploy_To_Cloud_Run'

logsBucket: 'gs://find-my-ip-467322-cloudbuild-logs'