steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg'
    - 'MAXMIND_ACCOUNT_ID=${_MAXMIND_ACCOUNT_ID}'
    - '--build-arg'
    - 'MAXMIND_LICENSE_KEY=${_MAXMIND_LICENSE_KEY}'
    - '-t'
    - 'gcr.io/${PROJECT_ID}/echoip'
    - '.'
  id: 'Build_New_Image_With_Latest_MaxMind_DB'
  timeout: '900s'
  # Remove 'env: ['DOCKER_BUILDKIT=1']' from here

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/${PROJECT_ID}/echoip'
  id: 'Push_Image_To_Container_Registry'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'echoip'
    - '--image'
    - 'gcr.io/${PROJECT_ID}/echoip'
    - '--project'
    - '${PROJECT_ID}'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
  id: 'Deploy_To_Cloud_Run'

logsBucket: 'gs://find-my-ip-467322-cloudbuild-logs' # Ensure this is your correct bucket name

# --- ADD THESE LINES AT THE VERY END, OR AT THE TOP LEVEL ---
options:
  requestedWorkerOption:
    pool:
      workerConfig:
        machineType: 'e2-medium' # You can choose a suitable machine type
  # This is the key part to enable BuildKit globally for the build
  docker:
    enableBuildkit: true